using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Currency;
//
//    var CurrencyFromJsonToClass = CurrencyFromJsonToClass.FromJson(jsonString);

namespace CurrencyCalculatorAPI.JSON
{


    public partial class CurrencyCalculatorApiJson
    {
        [JsonProperty("table")]
        public string Table { get; set; }

        [JsonProperty("no")]
        public string No { get; set; }

        [JsonProperty("effectiveDate")]
        public DateTimeOffset EffectiveDate { get; set; }

        [JsonProperty("rates")]
        public Rate[] Rates { get; set; }
    }


    public partial class CurrencyCalculatorApiJson
    {
        public static CurrencyCalculatorApiJson[] FromJson(string json) => JsonConvert.DeserializeObject<CurrencyCalculatorApiJson[]>(json, Converter.Settings);
    }





}
